# Generated by Django 5.2.7 on 2025-10-21 12:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('clickup', 'ClickUp'), ('jira', 'Jira'), ('asana', 'Asana'), ('trello', 'Trello'), ('monday', 'Monday')], max_length=20)),
                ('external_project_id', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('sync_mode', models.CharField(choices=[('import_once', 'Import Once'), ('read_only', 'Read Only'), ('controlled', 'Controlled Sync')], default='import_once', max_length=20)),
                ('scope_locked', models.BooleanField(default=False)),
                ('baseline_task_ids', models.JSONField(default=list)),
                ('baseline_task_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(max_length=50)),
                ('priority', models.CharField(blank=True, max_length=50, null=True)),
                ('provider', models.CharField(max_length=20)),
                ('external_id', models.CharField(max_length=255)),
                ('external_url', models.URLField(blank=True, null=True)),
                ('in_baseline', models.BooleanField(default=False)),
                ('scope_approved', models.BooleanField(default=True)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('time_tracked', models.FloatField(default=0)),
                ('payment_status', models.CharField(default='unpaid', max_length=20)),
                ('custom_fields', models.JSONField(default=dict)),
                ('assigned_freelancer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.project')),
            ],
        ),
    ]
