# Generated by Django 5.2.7 on 2025-10-23 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_remove_project_provider_remove_task_provider_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='custom_fields',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
