# Generated by Django 5.2.7 on 2025-10-23 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_task_custom_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='custom_fields',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
