# Generated by Django 5.2.7 on 2025-10-23 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_task_custom_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerconnection',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
